### PR TITLE
Kubelet metrics cardinality

### PR DESCRIPTION
**Pull request by paulfantom**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

The label seems to be unused, but it can cause issues with high cardinality. On k3s this label has unbound cardinality due to the inclusion of url param like `timout`. Examples from my small k3s cluster:

Screenshot from 2021-11-10 19-03-23

query `count by (url) ({url=~".+", job="kubelet", url=~".*timeout.*"})` returns:
```
...


{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m0s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
-- | --
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m11s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m19s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m1s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m24s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m27s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m28s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m2s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m31s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m32s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m33s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m34s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m35s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m37s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m38s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m3s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m40s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m41s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m42s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m45s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m46s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m47s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m49s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m4s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m51s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m52s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m53s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m56s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m58s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m59s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m6s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m8s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=5m9s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m0s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m10s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m1s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m23s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m24s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m27s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m31s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m33s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m37s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m41s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m43s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m44s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m46s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m49s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 26
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m51s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
{url="https://127.0.0.1:6444/api/v1/namespaces/%7Bnamespace%7D/configmaps?allowWatchBookmarks=%7Bvalue%7D&fieldSelector=%7Bvalue%7D&resourceVersion=%7Bvalue%7D&timeout=6m55s&timeoutSeconds=%7Bvalue%7D&watch=%7Bvalue%7D"} | 13
...
```

Testing in https://github.com/thaum-xyz/ankhmorpork/commit/97069a88b1e5386b2eab5205d334fe6ab5e6789d

## Type of change

_What type of changes does your code introduce to the kube-prometheus? Put an `x` in the box that apply._

- [x] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. Later this will be copied to the changelog file._

```release-note
Drop `url` label from kubelet metrics
```

### CODE REVIEW

**Comment by simonpasquier** [comment]
Can you confirm that the label is set for `rest_client_*` metrics?
`count by (__name__) ({url=~".+", job="kubelet"})` returns this on a cluster of mine:

```
rest_client_request_duration_seconds_count{} | 424
rest_client_request_duration_seconds_sum{} | 424
rest_client_rate_limiter_duration_seconds_bucket{} | 3817
rest_client_rate_limiter_duration_seconds_count{} | 347
rest_client_rate_limiter_duration_seconds_sum{} | 347
rest_client_request_duration_seconds_bucket{} | 4664
```

I suspect that dropping the url label would lead to duplicate series. Maybe best to drop the series?

**Comment by paulfantom** [comment]
`rest_client_.*` series are used in some alerts (example: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/kubernetes-prometheusRule.yaml#L443-L456), so dropping them is not ideal.

Regarding duplicates, maybe I should just relabel value of the label to drop everything after `?` sign in url? This way all request parameters would be dropped and url wouldn't mutate. WDYT?

**Comment by simonpasquier** [comment]
> Regarding duplicates, maybe I should just relabel value of the label to drop everything after ? sign in url? This way all request parameters would be dropped and url wouldn't mutate. WDYT?

I'm not sure it would suffice since `url="http://example.com/foo?timeout=10s" and `url="http://example.com/foo?timeout=30s"` would end up being the same value.

The issue should probably be raised to the Kubernetes community (SIG instrumentation?): the cardinality of these metrics is problematic and at the minimum, the query part shouldn't appear in the label value.

cc @dgrisonnet @jan--f @fpetkovski

**Comment by dgrisonnet** [comment]
> The issue should probably be raised to the Kubernetes community (SIG instrumentation?)

+1. I can bring that up.

The first thing that strikes me is that the timeout value seems to be variable whilst I would expect its value to be constant.

Also, I wonder if it is really meaningful in latency metrics to have the timeout value. I can hardly see any use case where that information can be used. It's not like we could identify the requests that timed out with histograms and we most likely also don't want to remove requests timing-out from the overall latency computation. So I think we should remove the timeout label, but that topic should definitely be brought to k/k.

**Comment by paulfantom** [comment]
> I'm not sure it would suffice since url="http://example.com/foo?timeout=10s" and url="http://example.com/foo?timeout=30s"` would end up being the same value.

That is the intended outcome. Both queries are targetting the same resource, hence for me, they should be in the same bucket even if they have different query parameters.

> I think we should try to figure out upstream why this value is changing so much.

I agree that this should be taken upstream (to sig-instrumentation). However, this quick fix would have an immediate effect of reducing cardinality.

**Comment by ehashman** [comment]
(kubelet maintainer here) This full URL should not have made it into a metric, this is a Kubernetes bug. We will fix this upstream.

**Comment by dgrisonnet** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/106539 in k/k. It will most likely be backported.

@paulfantom could you try to track down the application that was making these queries? The variable timeout value is really weird and from what @simonpasquier shared in https://github.com/prometheus-operator/kube-prometheus/pull/1499#issuecomment-972928587 it doesn't seem to impact OCP so there might an application in your cluster that is making weird queries to kubelet.

**Comment by simonpasquier** [comment]
Thanks @ehashman for chiming in and confirming my intuition :)

> That is the intended outcome. Both queries are targetting the same resource, hence for me, they should be in the same bucket even if they have different query parameters.

@paulfantom I'm not sure why you don't see duplicate series errors with your metric relabeling config. If I run `label_replace(rest_client_rate_limiter_duration_seconds_bucket, "url", "$1", "url", "(.*)\\?.*")` on an OCP 4.9 cluster, it errors out with `Error executing query: vector cannot contain metrics with the same labelset`.

@dgrisonnet the same issue exists on OCP 4.9 (at least I haven't checked previous versions).

**Comment by simonpasquier** [comment]
> The first thing that strikes me is that the timeout value seems to be variable whilst I would expect its value to be constant.

I bet that these are watch requests.

**Comment by djsly** [comment]
> (kubelet maintainer here) This full URL should not have made it into a metric, this is a Kubernetes bug. We will fix this upstream.

@ehashman would you have by any chance a issue number I could track ?

**Pull request closed without merging**
