### PR TITLE
Add a guide for adding Prometheus Push Gateway 

### PR DESCRIPTION
**Pull request by latchmihay**
- Update docs on adding prometheus push gateway

### CODE REVIEW

**Comment by metalmatze** [comment]
This documentation should be in your project. As long as we don't have anything Prometheus Push Gateway related in this repo, I don't think we should merge this. 
Thanks for working on this as a community project nevertheless!

**Comment by latchmihay** [comment]
Yes, I do have the documentation in my project. This is simply to direct the community with instructions on how to consume it

**Comment by HtcOrange** [comment]
@latchmihay  I successfully add  Prometheus Push Gateway and I can see the pod of prometheus-pushgateway running, but when I enter the port 30007,  it shows that "prometheus-pushgateway/0 (0/0 up)".Why is that so? Look forward to your favourable reply!

**Comment by latchmihay** [comment]
@HtcOrange I am not sure what you mean. You should have a service listening on 9091 thats it. Also you should see it in your prometheus targes and service discovery

**Comment by billykwooten** [comment]
Any update on this? I am not sure why this hasn't been implemented yet. Prometheus gateway is an solution from the Prometheus team themselves, currently kube-prometheus doesn not support it.

**Comment by paulfantom** [comment]
For people looking for an answer on how to add PGW in jsonnet, here is a lib: https://github.com/thaum-xyz/ankhmorpork/blob/d2270a7675c927a72cee15d2fe68815f38eb0467/apps/monitoring/jsonnet/lib/pushgateway.libsonnet. It will most likely be moved to some other place later on, but I doubt it will be in kube-prometheus. This is because PGW doesn't complement prometheus-operator stack in any way and it only creates an easier path to abusing prometheus.

**Comment by paulfantom** [comment]
I am closing this as such documentation should be in https://github.com/latchmihay/kube-prometheus-pushgateway and not in kube-prometheus solely because of the fact that kube-prometheus is not shipping the component.

**Pull request closed without merging**
