### PR TITLE
Test against Kubernetes 1.22

### PR DESCRIPTION
**Pull request by dgrisonnet**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Updated kind version and kind images according to https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1

## Type of change

_What type of changes does your code introduce to the kube-prometheus? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. Later this will be copied to the changelog file._

```release-note

```

### CODE REVIEW

**Comment by paulfantom** [comment]
Let's enable that after cutting `release-0.9`, ok?

**Comment by paulfantom** [comment]
We should disable 1.20 when enabling 1.22. It might be good to have 1.22 in `release-0.9`, so we have `release-0.8` supporting 1.20 and 1.21, whereas `release-0.9` would be supporting 1.21 and 1.22. Thoughts on this?

---

>  main_test.go:138: deprecated metric with name: etcd_object_counts and help text: [ALPHA] (Deprecated since 1.22.0) Number of stored objects at the time of last check split by kind. This metric is replaced by apiserver_storage_object_counts. exists.

Metric `etcd_object_counts` should be added to https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/addons/dropping-deprecated-metrics-relabelings.libsonnet

**Comment by dgrisonnet** [comment]
Make sense to me, I'll hold this PR until the next release is cut.

**Review by paulfantom — APPROVED** [review]
lgtm on green

**Pull request merged**
