### PR TITLE
WIP: Validate manifests using kubeval

### PR DESCRIPTION
**Pull request by kakkoyun**
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

Add [kubeval](https://www.kubeval.com) as a validation method for generated manifests.

`Work in progress`: Still entertaining the idea. However, I'd like to hear what maintainers think.

### CODE REVIEW

**Comment by brancz** [comment]
Neat!

**Comment by paulfantom** [comment]
> How does this work with CRDs?

Sadly it doesn't. There is an open issue in kubeval project to support non-native objects: https://github.com/instrumenta/kubeval/issues/47

**Review by paulfantom — APPROVED** [review]
Idea LGTM

**Comment by yannh** [comment]
Hi there :wave: I've been working on kubeconform ( https://github.com/yannh/kubeconform/ ) - which is very similar to kubeval, and adds support for CRDs. Maybe I can help?

**Comment by kakkoyun** [comment]
@yannh That would be awesome. Project needs a good validation strategy since we are moving away from ksonnet. I'll be checking the `kubeconform`. We could use it for other projects as well. Tell me if I can help in any way.

**Comment by yannh** [comment]
Mhhh one thing I'm missing is a stable interface to use kubeconform as a library. I'll try to work on that soon.

**Comment by yannh** [comment]
The approach of Kubeval/Kubeconform to do validation is to use Json Schemas, generated from the OpenAPI Spec files. For Kubeconform to be able to validate Custom Resources, the Json Schemas need to be accessible either via HTTP or the local filesystem. What would be the best approach here - commit the JSON Schemas to this repo? Note that the only tool I have at the moment to convert from OpenAPI to Json Schema is in Python.

**Comment by yannh** [comment]
Alright, started some work here https://github.com/prometheus-operator/kube-prometheus/pull/785
I validated manifests/ using JSON schemas generated from the CRDs here: https://github.com/prometheus-operator/prometheus-operator/tree/master/example/prometheus-operator-crd

I ran the validation in "strict" mode, which means it complains for properties found that were not specified in the Spec. Now this is quite verbose and I will need to dig in those errors individually to validate them...

```$ /home/yann/go/src/github.com/yannh/kubeconform/bin/kubeconform -summary -schema-location '/home/yann/go/src/github.com/prometheus-operator/kube-prometheus/manifests/schemas/alertmanager_{{ .ResourceAPIVersion }}.json' manifests/*.yaml
manifests/alertmanager-serviceAccount.yaml - ServiceAccount alertmanager-main is invalid: spec is required
manifests/alertmanager-secret.yaml - Secret alertmanager-main is invalid: spec is required
manifests/grafana-dashboardDefinitions.yaml - failed validation: bufio.Scanner: token too long
manifests/alertmanager-serviceMonitor.yaml - ServiceMonitor alertmanager is invalid: Additional property endpoints is not allowed - Additional property selector is not allowed
manifests/grafana-dashboardDatasources.yaml - Secret grafana-datasources is invalid: spec is required
manifests/grafana-serviceAccount.yaml - ServiceAccount grafana is invalid: spec is required
manifests/grafana-serviceMonitor.yaml - ServiceMonitor grafana is invalid: Additional property endpoints is not allowed - Additional property selector is not allowed
manifests/grafana-dashboardSources.yaml - ConfigMap grafana-dashboards is invalid: spec is required
manifests/alertmanager-service.yaml - Service alertmanager-main is invalid: Additional property ports is not allowed - Additional property selector is not allowed - Additional property sessionAffinity is not allowed
manifests/grafana-service.yaml - Service grafana is invalid: Additional property ports is not allowed - Additional property selector is not allowed - Additional property type is not allowed
manifests/grafana-deployment.yaml - Deployment grafana is invalid: Additional property selector is not allowed - Additional property template is not allowed
manifests/kube-state-metrics-serviceAccount.yaml - ServiceAccount kube-state-metrics is invalid: spec is required
manifests/kube-state-metrics-serviceMonitor.yaml - ServiceMonitor kube-state-metrics is invalid: Additional property endpoints is not allowed - Additional property jobLabel is not allowed - Additional property selector is not allowed
manifests/kube-state-metrics-service.yaml - Service kube-state-metrics is invalid: Additional property selector is not allowed - Additional property clusterIP is not allowed - Additional property ports is not allowed
manifests/kube-state-metrics-clusterRoleBinding.yaml - ClusterRoleBinding kube-state-metrics is invalid: spec is required
manifests/kube-state-metrics-deployment.yaml - Deployment kube-state-metrics is invalid: Additional property selector is not allowed - Additional property template is not allowed
manifests/node-exporter-clusterRole.yaml - ClusterRole node-exporter is invalid: spec is required
manifests/kube-state-metrics-clusterRole.yaml - ClusterRole kube-state-metrics is invalid: spec is required
manifests/node-exporter-serviceAccount.yaml - ServiceAccount node-exporter is invalid: spec is required
manifests/node-exporter-service.yaml - Service node-exporter is invalid: Additional property clusterIP is not allowed - Additional property ports is not allowed - Additional property selector is not allowed
manifests/node-exporter-serviceMonitor.yaml - ServiceMonitor node-exporter is invalid: Additional property jobLabel is not allowed - Additional property selector is not allowed - Additional property endpoints is not allowed
manifests/prometheus-adapter-clusterRoleAggregatedMetricsReader.yaml - ClusterRole system:aggregated-metrics-reader is invalid: spec is required
manifests/prometheus-adapter-clusterRoleBindingDelegator.yaml - ClusterRoleBinding resource-metrics:system:auth-delegator is invalid: spec is required
manifests/prometheus-adapter-clusterRoleBinding.yaml - ClusterRoleBinding prometheus-adapter is invalid: spec is required
manifests/prometheus-adapter-clusterRoleServerResources.yaml - ClusterRole resource-metrics-server-resources is invalid: spec is required
manifests/prometheus-adapter-clusterRole.yaml - ClusterRole prometheus-adapter is invalid: spec is required
manifests/prometheus-adapter-configMap.yaml - ConfigMap adapter-config is invalid: spec is required
manifests/node-exporter-clusterRoleBinding.yaml - ClusterRoleBinding node-exporter is invalid: spec is required
manifests/prometheus-adapter-deployment.yaml - Deployment prometheus-adapter is invalid: Additional property template is not allowed - Additional property selector is not allowed - Additional property strategy is not allowed
manifests/prometheus-adapter-serviceAccount.yaml - ServiceAccount prometheus-adapter is invalid: spec is required
manifests/prometheus-adapter-serviceMonitor.yaml - ServiceMonitor prometheus-adapter is invalid: Additional property endpoints is not allowed - Additional property selector is not allowed
manifests/prometheus-adapter-service.yaml - Service prometheus-adapter is invalid: Additional property ports is not allowed - Additional property selector is not allowed
manifests/prometheus-clusterRoleBinding.yaml - ClusterRoleBinding prometheus-k8s is invalid: spec is required
manifests/prometheus-clusterRole.yaml - ClusterRole prometheus-k8s is invalid: spec is required
manifests/prometheus-operator-serviceMonitor.yaml - ServiceMonitor prometheus-operator is invalid: Additional property endpoints is not allowed - Additional property selector is not allowed
manifests/node-exporter-daemonset.yaml - DaemonSet node-exporter is invalid: Additional property selector is not allowed - Additional property template is not allowed - Additional property updateStrategy is not allowed
manifests/prometheus-adapter-apiService.yaml - APIService v1beta1.metrics.k8s.io is invalid: Additional property versionPriority is not allowed - Additional property group is not allowed - Additional property groupPriorityMinimum is not allowed - Additional property insecureSkipTLSVerify is not allowed - Additional property service is not allowed
manifests/prometheus-adapter-roleBindingAuthReader.yaml - RoleBinding resource-metrics-auth-reader is invalid: spec is required
manifests/prometheus-prometheus.yaml - Prometheus k8s is invalid: Additional property serviceMonitorSelector is not allowed - Additional property alerting is not allowed - Additional property probeNamespaceSelector is not allowed - Additional property podMonitorSelector is not allowed - Additional property ruleSelector is not allowed - Additional property serviceMonitorNamespaceSelector is not allowed - Additional property podMonitorNamespaceSelector is not allowed - Additional property probeSelector is not allowed
manifests/prometheus-roleBindingConfig.yaml - RoleBinding prometheus-k8s-config is invalid: spec is required
manifests/prometheus-serviceAccount.yaml - ServiceAccount prometheus-k8s is invalid: spec is required
manifests/prometheus-rules.yaml - failed validation: bufio.Scanner: token too long
manifests/prometheus-roleBindingSpecificNamespaces.yaml - RoleBindingList  is invalid: spec is required
manifests/prometheus-serviceMonitorCoreDNS.yaml - ServiceMonitor coredns is invalid: Additional property endpoints is not allowed - Additional property jobLabel is not allowed - Additional property namespaceSelector is not allowed - Additional property selector is not allowed
manifests/prometheus-serviceMonitorApiserver.yaml - ServiceMonitor kube-apiserver is invalid: Additional property endpoints is not allowed - Additional property jobLabel is not allowed - Additional property namespaceSelector is not allowed - Additional property selector is not allowed
manifests/prometheus-roleConfig.yaml - Role prometheus-k8s-config is invalid: spec is required
manifests/prometheus-serviceMonitorKubeScheduler.yaml - ServiceMonitor kube-scheduler is invalid: Additional property selector is not allowed - Additional property endpoints is not allowed - Additional property jobLabel is not allowed - Additional property namespaceSelector is not allowed
manifests/prometheus-serviceMonitorKubeControllerManager.yaml - ServiceMonitor kube-controller-manager is invalid: Additional property jobLabel is not allowed - Additional property namespaceSelector is not allowed - Additional property selector is not allowed - Additional property endpoints is not allowed
manifests/prometheus-serviceMonitor.yaml - ServiceMonitor prometheus is invalid: Additional property endpoints is not allowed - Additional property selector is not allowed
manifests/prometheus-service.yaml - Service prometheus-k8s is invalid: Additional property ports is not allowed - Additional property selector is not allowed - Additional property sessionAffinity is not allowed
manifests/prometheus-serviceMonitorKubelet.yaml - ServiceMonitor kubelet is invalid: Additional property namespaceSelector is not allowed - Additional property selector is not allowed - Additional property endpoints is not allowed - Additional property jobLabel is not allowed
manifests/prometheus-roleSpecificNamespaces.yaml - RoleList  is invalid: spec is required
Summary: 53 resources found in 53 files - Valid: 1, Invalid: 50, Errors: 2, Skipped: 0```

Note that it failed on a couple of files because of their size, I will have to finetune kubeconform for those cases (it uses a bufio.scanner which has a fixed size buffer)

**Comment by paulfantom** [comment]
> manifests/prometheus-prometheus.yaml - Prometheus k8s is invalid: Additional property alerting is not allowed - Additional property serviceMonitorSelector is not allowed - Additional property probeNamespaceSelector is not allowed - Additional property ruleSelector is not allowed - Additional property podMonitorSelector is not allowed - Additional property probeSelector is not allowed - Additional property serviceMonitorNamespaceSelector is not allowed - Additional property podMonitorNamespaceSelector is not allowed

This is not right as those properties are allowed by Prometheus CRD: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec

I checked a few others and it seems like either Kubeconform has some false positives in its output or prometheus-operator has invalid schemas. :thinking: 

PS. @yannh awesome project!

**Comment by yannh** [comment]
Kubeconform is (I think) rather solid, but my script to convert OpenAPI to JSON schema is a bit brittle :) I will investigate these in details soon.

**Comment by yannh** [comment]
My command line was wrong, I forgot I hard hardcoded the path to alertmanager_{{ .ResourceAPIVersion }}.json  while debugging.
This works now:

```
$ ~/go/src/github.com/yannh/kubeconform/bin/kubeconform -kubernetes-version 1.18.0 -summary -schema-location 'https://kubernetesjsonschema.dev' -schema-location '/home/yann/go/src/github.com/prometheus-operator/kube-prometheus/manifests/schemas/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json' manifests/*.yaml
Summary: 53 resources found in 53 files - Valid: 53, Invalid: 0, Errors: 0, Skipped: 0
```

**Comment by kakkoyun** [comment]
Closing this one for the sake of #785. Let's continue the discussion on that PR. Amazing work @yannh, thanks a lot.

**Pull request closed without merging**
