### PR TITLE
Remove mutating global state in prometheus-adapter objects

### PR DESCRIPTION
**Pull request by paulfantom**
Same as #857 but for prometheus-adapter.

Part of #566.

WIP until #857 is merged and I rebase this PR.

### CODE REVIEW

**Comment by paulfantom** [comment]
#857 is merged, this PR is ready for review.
/cc @prometheus-operator/kube-prometheus-reviewers

**Review by kakkoyun — APPROVED** [review]
LGTM 🥇

**Review by lilic — APPROVED** [review]
Thanks!

**Comment by paulfantom** [comment]
Rebased to fix merge conflicts. I expect this to happen every time we merge one of PRs with the refactor :shrug:

**Comment by paulfantom** [comment]
I merged this as CI was green and the only change was a rebase.

**Pull request merged**
