### PR TITLE
[bot] Automated version update

### PR DESCRIPTION
**Pull request by paulfantom**
This is an automated version update performed from CI on behalf of @paulfantom.

Configuration of the workflow is located in `.github/workflows/versions.yaml`

### CODE REVIEW

**Review by ArthurSens — APPROVED** [review]
Is there a checklist for things we want to check before approving these automated PRs?

I'm deploying the generated PRs into a cluster, but I'm not entirely sure if I'm checking everything.


```
kubectl apply -f manifests/setup/
kubectl apply -f manifests/
```
Worked out of the box, Everything seems to be running smoothly, so I'm approving this one

**Comment by ArthurSens** [comment]
Grafana 8.0.0 😍 

image

**Comment by paulfantom** [comment]
> Is there a checklist for things we want to check before approving these automated PRs?

It is the same as with manual version bumps. The manifests generation is checked in CI, but major version bumps should be evaluated manually when possible.

> Grafana 8.0.0

I would like to have more opinions on this. Grafana 8.0 is AGPL licensed and this may pose some problems for other folks. We may want to still ship 8.0, but create some jsonnet example on how to exclude grafana from being deployed and maybe note in the documentation that non-AGPL version of grafana can be used by changing `image`.

**Comment by paulfantom** [comment]
I would like to have https://github.com/prometheus-operator/kube-prometheus/pull/1201 before merging this PR as this offers a way to disable grafana for folks who don't want to use it (for example due to licensing issues)

**Comment by paulfantom** [comment]
Let's do this!

For future reference:

- if one don't want to install grafana, one can use https://github.com/prometheus-operator/kube-prometheus/blob/main/examples/grafana-only-dashboards.jsonnet to disable all grafana-related objects apart from dashboards
- if one cannot use grafana 8.0+, for example due to AGPL licensing issues, consider changing `$.grafana.image` to one which provides older grafana version
- if you want to have dashboards, but don't want to have grafana 8 nor can use grafana 7, consider resurrecting https://github.com/spartanaorg/spartana

**Pull request merged**
