### PR TITLE
[release-0.6]: Bump to prometheus-operator 0.42.1

### PR DESCRIPTION
**Pull request by lilic**

### CODE REVIEW

**Review by paulfantom — COMMENTED** [review]
This seems like a bit more than just a bump of prometheus-operator.

**Comment by lilic** [comment]
@paulfantom yeah I ran jb update, the main reason to bump everything was to bring in Prometheus operator, hope that clarifies it? Would you prefer me to change the title as per the commits or what is your suggestion?

**Comment by paulfantom** [comment]
I am fine with it as is. It wasn't clear at the first glance why kubernetes-mixin or node-exporter mixin are updated when PR states it is about prometheus-operator.

lgtm on green

**Comment by lilic** [comment]
@paulfantom got it, thanks! I tend to bump everything just so we don't have to do it too often as we already pin anyways to specific versions.

**Pull request merged**
