### PR TITLE
Manifests directory layout simplifications

### PR DESCRIPTION
**Pull request by paulfantom**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

I took a look at what is the most commonly accessed directory in this repository and just after `/`, it is `manifests/` directory. For this reason, I would like to improve UX side of this directory.

What is done here:
- simpler `examples/kustomize.jsonnet` which remove the need to explicitly state what components need to be rendered and instead it uses all visible components mentioned in [`main.jsonnet`](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/main.libsonnet). As a side effect all filenames are now using component names from jsonnet (which should help in the long run).
- only true setup manifests are put into `manifests/setup` directory. This way prometheus-operator can be updated separately from CRDs and namespace.

PR is partially built on top of some concepts from https://github.com/prometheus-operator/kube-prometheus/pull/1021 and lessons learned from https://github.com/thaum-xyz/ankhmorpork.

## Type of change

_What type of changes does your code introduce to the kube-prometheus? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. Later this will be copied to the changelog file._

```release-note
store only CRDs and namespace definition in 'manifests/setup'
```

### CODE REVIEW

**Comment by paulfantom** [comment]
Next, possible step would be to put all components into a separate directory and recommend using `kubectl apply -R -f` to apply manifests. But I will take a stab at this later.

**Comment by ArthurSens** [comment]
I like this very much! In fact, we do something super similar downstream :)

The only thing that comes up to my mind is that we also need to modify the pod-security-policy addon. The policies are also required to be deployed before all components

**Comment by paulfantom** [comment]
>  The policies are also required to be deployed before all components

That's weird, can you elaborate why is that a case? I was under impression that we only need to have Namespace (to put stuff into) and CRDs (to have APIs) first and the rest is taken care of by the declarative configuration management native to kubernetes . Afaik this is also how Helm install stuff.

Ideally we shouldn't be doing any imperative configuration management in kubernetes, but the world is not ideal :(

**Comment by ArthurSens** [comment]
> That's weird, can you elaborate why is that a case? I was under impression that we only need to have Namespace (to put stuff into) and CRDs (to have APIs) first and the rest is taken care of by using declarative configuration management native to kubernetes . Afaik this is also how Helm install stuff.
> 
> Ideally we shouldn't be doing any imperative configuration management in kubernetes, but the world is not ideal :(

I just checked again why we deploy the policies first, and I agree it shouldn't be a huge problem not adding them to "setup"

Downstream, we split manifests into folders (one per component). There is one single [object that is added to the `kube-prometheus` object](https://github.com/prometheus-operator/kube-prometheus/blob/8ed8f7014824dcfe7d0bb5fb548b60ef8f364bfd/jsonnet/kube-prometheus/addons/podsecuritypolicies.libsonnet#L54) and we just keep forgetting to deploy it because we don't really care much about the kube-prometheus folder. So what we did was move it to the "setup" folder instead.

This shouldn't happen here, so it's all good 👍

**Comment by paulfantom** [comment]
rebased to fix merge conflicts

**Review by ArthurSens — APPROVED** [review]

**Comment by ArthurSens** [comment]
Merging quickly because this one is easy to have conflicts 😅

**Pull request merged**
