### PR TITLE
Add changelogs to automated version updates

### PR DESCRIPTION
**Pull request by dgrisonnet**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Add the links to the changelogs of the freshly updated components to the
automated PR that does the update. This allow verifying that we are not
missing any important changes before merging the update. This happened
recently with node-exporter 1.2 which changed some flag names that we
took 3 months to update. https://github.com/prometheus-operator/kube-prometheus/pull/1407

## Type of change

_What type of changes does your code introduce to the kube-prometheus? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. Later this will be copied to the changelog file._

```release-note

```

### CODE REVIEW

**Comment by jan--f** [comment]
Nice addition! Lgtm.

**Review by ArthurSens — APPROVED** [review]
That's nice, a good addition to the review process!

I'm wondering if we could raise those concerns more loudly with e2e tests within our CI? Not sure how possible this is though... maybe checking for specific log messages when we're using deprecated flags? Either way, having the changelog available in the PRs is already a good step :)

**Comment by dgrisonnet** [comment]
Yeah having a test checking for the `deprecated` keyword in the logs might already be a good step forward. :+1:

**Pull request merged**
