### PR TITLE
Enable jsonnet linter

### PR DESCRIPTION
**Pull request by paulfantom**
As in title

/cc @kakkoyun

### CODE REVIEW

**Comment by paulfantom** [comment]
Currently blocked due to potential issue with linter itself. More on slack: https://kubernetes.slack.com/archives/C6JLE4L9X/p1606223369072100

**Comment by brancz** [comment]
:heart_eyes:

**Comment by paulfantom** [comment]
Rebased and no longer a WIP.

@kakkoyun  ping :)

**Comment by kakkoyun** [comment]
@paulfantom Looks good. However, CI fails with formatting issues.

**Comment by paulfantom** [comment]
Too many rebases and I lost one operation (`make fmt`) :facepalm: Now it should work.

**Review by kakkoyun — APPROVED** [review]
LGTM 👍 🚀

**Pull request merged**
