### PR TITLE
Update node-exporter with PodSecurityPolicies

### PR DESCRIPTION
**Pull request by latchmihay**
- add pod security role to the node-exporter clusterRole
- add pod security policy for node-exporter

### CODE REVIEW

**Comment by brancz** [comment]
Thanks for all your awesome PRs! Because of how jsonnet-bundler works today, we need the jsonnet changes to be in one commit, and the bump of the jsonnet dependency in a separate commit (this is being fixed with https://github.com/jsonnet-bundler/jsonnet-bundler/pull/36). Instructions how to do it now: https://github.com/coreos/kube-prometheus#contributing

**Comment by latchmihay** [comment]
I wasn't too sure how that work when its coming from a fork and what the dependency versions actually updates to. When I tried I saw the versions changed on almost all of the dependencies in the lock file, and that didnt seem right to me.

Can you provide me with step by step instructions I am happy to do it

**Comment by brancz** [comment]
from the tip of this PR run

```
jb update
```

this will update the kube-prometheus dependency within this repo, and then you just commit that in a separate commit

**Comment by metalmatze** [comment]
Can you rebase your PR one more time? We have finally gotten rid of the local dependency workaround and there shouldn't be another conflict with `jsonnetfile.lock.json` again.

Make sure to `go get -u github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb` to install the latest version of jb for a new needed feature.

**Comment by latchmihay** [comment]
I followed your instructions and recommited the latest `jsonetfile.lock.json` but there are still conflicts.
Not sure how I should resolve

**Comment by LiliC** [comment]
@latchmihay you need to first rebase your PR to master upstream branch, then run `jb update` in the `jsonnet/kube-prometheus ` directory and then run `make generate-in-docker` from the root dir.

**Comment by latchmihay** [comment]
thank you. I have rebased and regenerated

**Comment by paulfantom** [comment]
I am closing this as PSPs are scheduled to be deprecated - https://github.com/kubernetes/kubernetes/pull/97171

Please reopen or open an issue if you feel this is something that should be worked on.

**Pull request closed without merging**
