### PR TITLE
increase default CPU values for main kube-rbac-proxy sidecar in kube-state-metrics

### PR DESCRIPTION
**Pull request by paulfantom**
Due to amount of data and restrictive resource settings, main kube-rbac-proxy is triggering CPUThrottlingHigh alert as well as massively delaying scrapes in prometheus. By increasing available CPU limits I got from 5s to 2s in prometheus scrape duration on a small k3s cluster.

I am creating PR now, but I need to do some more testing as CPUThrottlingHigh is still firing with a value of >80.

### CODE REVIEW

**Comment by paulfantom** [comment]
Related to https://github.com/thaum-xyz/ankhmorpork/pull/69

**Comment by brancz** [comment]
Any reason why this is WIP?

**Comment by paulfantom** [comment]
Yes, I was running this for the last 7 days and the scrape duration fell a bit but rbac proxy is still throttling. I'll try to take a closer look at it, but not committing to this now due to lack of time.

**Comment by brancz** [comment]
CPU throttling is an info alert no? Is there really a problem with it? We send info alert to /dev/null until negative matching is released for inhibition rules in Alertmanager, at which point we'll be able to inhibit info alerts unless any other ones are firing.

**Comment by paulfantom** [comment]
> CPU throttling is an info alert no?

Yes it is. However, in this case giving more CPU to kube-rbac-proxy means, we can have faster scrapes of kube-state-metrics data.

**Comment by brancz** [comment]
I can see how that could happen yes. Do you have data showing that this actually makes a difference?

**Comment by paulfantom** [comment]
Screenshot_20210223_091028

I reverted this change on my small cluster and here is the output. Blue is **after** applying this change, yellow is **before**

**Comment by paulfantom** [comment]
Adding another 20m CPU doesn't change much.

```
                       requests+: { cpu: '40m' },
                       limits+: { cpu: '60m' },
```

Screenshot_20210223_093408

red - `limits: { cpu: '20m' }`
yellow - `limits: { cpu: '40m' }`
blue - `limits: { cpu: '60m' }`

**Comment by paulfantom** [comment]
Removed WIP and formatted jsonnet code. Further increasing CPU limit doesn't seem to affect scrape duration. CPUThrottlingHigh alert will still fire but it is only an informative alert.

**Comment by brancz** [comment]
Wow nice! Always trust the data!

lgtm :+1:

**Pull request merged**
