### PR TITLE
Add PodDisruptionBudget objects

### PR DESCRIPTION
**Pull request by paulfantom**
Making sure there is always one prometheus replica and that alertmanager cluster is up and running. Those settings should ensure monitoring is operational during upgrades.

### CODE REVIEW

**Comment by brancz** [comment]
lgtm, nice work! :+1: :tada:

**Comment by ArthurSens** [comment]
What if someone uses only 1 replica? Does that prevent upgrades at all?

**Comment by paulfantom** [comment]
In my tests it didn't prevent StatefulSet updates and pods were rotated as expected.

**Comment by coderanger** [comment]
I think @ArthurSens is correct, PDBs don't impact upgrades at the StS level, but this would block a node drain if only replica is in use. Which means it will block k8s upgrades and whatnot.

**Comment by paulfantom** [comment]
Makes sense. What if we apply PDB conditionally? Since we already have a config field for `replicas` we can use it and apply PDB only if `replicas > 1`.

More in https://github.com/prometheus-operator/kube-prometheus/pull/1036

**Pull request merged**
