### PR TITLE
Enable Multi Cluster alerts by default

### LINKED ISSUE #2056: Add support for multi cluster alert rule queries
**What is missing?**

A Bunch of Prometheus alert rules do not support multi-cluster setup. For example [KubeAPITerminatedRequests](https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/kubernetesControlPlane-prometheusRule.yaml#L580) should group metric by cluster, ie. `sum by (cluster) (rate(apiserver_request_terminations_total{job="apiserver"}[10m]))  / (  sum by (cluster) (rate(apiserver_request_total{job="apiserver"}[10m])) + sum by (cluster) (rate(apiserver_request_terminations_total{job="apiserver"}[10m])) ) > 0.20`.

List of alerts lacking multi-cluster support:
- KubeCPUQuotaOvercommit
- KubeMemoryQuotaOvercommit
- KubeStateMetricsListErrors
- KubeStateMetricsShardingMismatch
- KubeStateMetricsShardsMissing
- KubeStateMetricsWatchErrors
- PrometheusOperatorListErrors
- PrometheusOperatorNotReady
- PrometheusOperatorReconcileErrors
- PrometheusOperatorWatchErrors
- TargetDown

**Why do we need it?**

**Environment**

* kube-prometheus version:

    `8.4.1`

**Anything else we need to know?**:

Other alerts already do support this, ie. https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/kubernetesControlPlane-prometheusRule.yaml#L551

### PR DESCRIPTION
**Pull request by jkroepke**
## Description

Fixes #2056

## Type of change

_What type of changes does your code introduce to the kube-prometheus? Put an `x` in the box that apply._

- [x] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. Later this will be copied to the changelog file._

```release-note
Enable Multi Cluster alerts by default
```

### CODE REVIEW

**Comment by jkroepke** [comment]
@philipgough  do you have some time for a review here?

**Comment by jkroepke** [comment]
@philipgough rebased.

**Comment by simonpasquier** [comment]
No objection from my side. Ideally it should be consistent and there should be a single config parameter in kube-prometheus while right now, it seems that some mixins support toggling multi-cluster on/off while for others, it's hard-coded.

**Review by philipgough — APPROVED** [review]
lgtm

**Comment by philipgough** [comment]
Thanks Simon, followed up with #2120 based on your comment

**Pull request merged**
