### PR TITLE
jsonnet/kube-prometheus: point to runbooks.prometheus-operator.dev

### PR DESCRIPTION
**Pull request by paulfantom**
Deprecating wiki in favor of a site (https://runbooks.thaum.xyz/) and [a new repo](https://github.com/prometheus-operator/runbooks)

### CODE REVIEW

**Comment by dgrisonnet** [comment]
shouldn't we point to https://runbooks.prometheus-operator.dev/ instead?

**Comment by paulfantom** [comment]
Right, I don't know why I pointed to that one :thinking:

**Comment by paulfantom** [comment]
@dgrisonnet Fixed :)

**Comment by paulfantom** [comment]
Resolved merge conflict.

**Review by dgrisonnet — APPROVED** [review]
LGTM

**Comment by dgrisonnet** [comment]
Just noticed the HTTP 404 page of https://runbooks.prometheus-operator.dev/, it's really nice! :open_mouth:

**Pull request merged**
