### PR TITLE
Update resources for prometheus

### PR DESCRIPTION
**Pull request by latchmihay**
- Add limits to the prometheus resources
- add default CPU to the request resources

### CODE REVIEW

**Comment by bgagnon** [comment]
See related MR #132

**Comment by latchmihay** [comment]
That is great I would love if similar mixin is available for the other components. 
In the change you referenced it only affects `'addon-resizer'`, `'kube-rbac-proxy'`, and `'node-exporter'` this PR is for the resources on `prometheus` instance it self

**Comment by bgagnon** [comment]
@latchmihay the optional mixin is for stripping the limits (issue #72) of certain contains with very small CFS allocations (which triggers false alarms of throttling), but normal customization or requests/limits is available without the mixin through the `_config` top-level property. The Prometheus requests and limits from this MR could move to the `_config` object without being added to the mixin.

**Comment by paulfantom** [comment]
Recent refactoring allows setting resources in an easier way (example). However, we cannot set any default values for memory limits of prometheus server as this is highly dependent on a number of ingested metrics and even small clusters can require a high amount of memory.

I recommend reading robustperception.io/how-much-ram-does-prometheus-2-x-need-for-cardinality-and-ingestion for more information on memory requirements.

Closing this. Please open an issue if you feel this still should be implemented.

**Pull request closed without merging**
