### PR TITLE
Refactor deprecated inhibit rules matchers

### PR DESCRIPTION
**Pull request by andrein**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Refactors alertmanager config to use the new `matcher` fields. 

## Type of change

_What type of changes does your code introduce to the kube-prometheus? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. Later this will be copied to the changelog file._

```release-note
Alertmanager now uses the new `matcher` syntax in the routing tree and inhibition rules.
```

### CODE REVIEW

**Review by paulfantom — APPROVED** [review]
lgtm

Let's just mark this as an `enhancement` in PR description.

**Comment by paulfantom** [comment]
@andrein could you also migrate matchers in `route`? Example https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/raw/alertmanager-secret.yaml#L132-L133

**Comment by andrein** [comment]
@paulfantom done. feel free to edit the changelog entry, i'm having trouble coming up with one that doesn't sound like `replace matchers with matchers`.

**Comment by paulfantom** [comment]
Thank you! :+1:

**Pull request merged**
