### PR TITLE
Fix wrong indentation for affinity rule

### PR DESCRIPTION
**Pull request by kakkoyun**
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

Fixes issue that raised in https://github.com/prometheus-operator/kube-prometheus/pull/760/files#r530871296

cc @zetaab

### CODE REVIEW

**Review by lilic — APPROVED** [review]
Thanks for the quick fix!

**Comment by lilic** [comment]
@zetaab can you verify this fixes your issue, thanks!

**Comment by paulfantom** [comment]
I think we need to start generating those patches and storing them somewhere for comparison in CI. This would prevent such issue from happening in the first place.

**Comment by lilic** [comment]
@paulfantom agreed we should improve CI, but could this not be fixed by https://github.com/prometheus-operator/kube-prometheus/pull/785?

**Comment by kakkoyun** [comment]
@lilic @paulfantom Big plus one to that. I'm going to try to jump on the #785 again, as soon as I can.

**Comment by paulfantom** [comment]
#785 will only validate manifests which we already have and we don't have generated manifests with anti-affinity. However, this would be a good start :+1:

Another approach would be to add some more example jsonnet files which include other patches (like this one) render manifests only in CI and run linter over them.

**Comment by brancz** [comment]
lgtm :+1: nice!

**Comment by lilic** [comment]
> Another approach would be to add some more example jsonnet files which include other patches (like this one) render manifests only in CI and run linter over them.

Yes 👍 on this one. We can improve on it if we need to in the future, but I believe this should be enough for now.

**Comment by zetaab** [comment]
Yeah this looks working one. Thanks!

**Pull request merged**
