### PR TITLE
make the alert rule better represent the alert

### PR DESCRIPTION
**Pull request by alam0rt**
https://github.com/prometheus-operator/kube-prometheus/issues/817

### CODE REVIEW

**Comment by alam0rt** [comment]
I ran the `make generate` command and it seems to have touched many files... Is this expected?

**Comment by simonpasquier** [comment]
> I ran the make generate command and it seems to have touched many files... Is this expected?

Not really. Maybe try reverting all changes except `jsonnet/kube-prometheus/kube-prometheus-eks.libsonnet` and run `make clean generate` again?

**Comment by alam0rt** [comment]
Alright - not sure what I did before but it's all good now. Reran `make generate` which produces 0 changes since EKS isn't a default option.

**Comment by brancz** [comment]
Awesome, thank you! lgtm :+1: :tada:

**Pull request merged**
