### PR TITLE
WIP: Validate manifests using Kubeconform 

### PR DESCRIPTION
**Pull request by yannh**
WIP, discussion happening in https://github.com/prometheus-operator/kube-prometheus/pull/775

### CODE REVIEW

**Comment by yannh** [comment]
@paulfantom  @kakkoyun "make validate" should work here, including validating the CRDs. The jsonschemas have been generated from the OpenAPI using this script: https://github.com/yannh/kubeconform/blob/master/scripts/openapi2jsonschema.py - I am not too sure if you want to be able to dynamically generate them somehow.

Do you think one of you could pick up from here? I am missing context on what exactly you want to validate and how this project works - however I would be happy to support and fix bugs should any be surfaced.

**Comment by kakkoyun** [comment]
@yannh Thanks a lot. I'll give it a shot. However I also don't want to be a blocker so if someone more eager than me wants to pick this one up, let me know.

**Comment by aweris** [comment]
@yannh @kakkoyun I would like to pick up if it's suitable for you.

**Comment by aweris** [comment]
Currently, I'm not able to focus on this topic. I'll return it a couple of weeks later. In the meantime, If anyone else wants to continue please feel free to pick up.

**Comment by paulfantom** [comment]
Rebasing turned out to be too complicated so I created an updated PR in https://github.com/prometheus-operator/kube-prometheus/pull/898 and closing this one.

**Pull request closed without merging**
