### PR TITLE
jsonnet: unify metadata management

### PR DESCRIPTION
**Pull request by paulfantom**
## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

To simplify code and reduce duplication this PR introduces hidden field `_metadata` which is then used to set metadata for all objects in a component.

This PR also cleans jsonnet codebase to first assign objects as value and then add data to that value. This way object won't be overriding explicit settings. Example: https://github.com/prometheus-operator/kube-prometheus/pull/1471/files#diff-9ada6ed45123a448cead005447e28c3d11af80858521ef7d85a7e0ea57e168daR153-R155

I am also starting to establish relations between objects in this PR as can be seen in `serviceAccountName` fields. This should further reduce code duplication and allow a better understanding of the codebase.

## Type of change

_What type of changes does your code introduce to the kube-prometheus? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

_Please put a one-line changelog entry below. Later this will be copied to the changelog file._

```release-note
Make metadata consistent across objects in the same component
```

### CODE REVIEW

**Comment by ArthurSens** [comment]
I like the approach of making explicit relationships in label selectors! Ping when you want to get a review here :)

**Comment by paulfantom** [comment]
@ArthurSens I fixed formatting issues and this should be ready as-is. I'll slowly introduce more relationships in future PRs.

**Review by ArthurSens — APPROVED** [review]
LGTM!

**Comment by ArthurSens** [comment]
I've noticed that a lot of resources were lacking metadata. Do you think it makes sense to add unit tests if we want to keep this consistent?

I've developed some tests downstream, e.g. [one that makes sure every alert has `severity` label](https://github.com/gitpod-io/gitpod/blob/main/operations/observability/mixins/tests/alertsSeverityLabel.jsonnet)

**Comment by paulfantom** [comment]
Yes, it would be awesome to add such tests! Do you want to add them? :)

**Pull request merged**
