### PR TITLE
Access requests to sidecar from thanos-query

### PR DESCRIPTION
**Pull request by polRk**
## Description
Current network polices restrict access to sidecar container from thanos query component. https://github.nmiku.com/thanos-io/kube-thanos/issues/272

## Type of change

_What type of changes does your code introduce to the kube-prometheus? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [x] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

Allow request from thanos-query to prometheus-operated service.

```release-note
 - Add NetworkPolicy rule allowing requests from thanos-query to prometheus-operated service.
```

### CODE REVIEW

**Comment by ArthurSens** [comment]
Hi @polRk, thanks for the fix!

Only one thing is missing, could you run `make generate` to make CI happy? 🙂

**Comment by ArthurSens** [comment]
Maybe we could add this patch only when Thanos is being used as well? Following the rule of least privileged, we don't want to give any access when it's not being used 🤔

**Comment by polRk** [comment]
> Maybe we could add this patch only when Thanos is being used as well? Following the rule of least privileged, we don't want to give any access when it's not being used 🤔

I've been thinking about it. We can enable this rule if the thanos object is specified?

**Review by ArthurSens — APPROVED** [review]
Thanks!

**Pull request merged**
